name: OnlyProxy
version: ${version}
main: net.dolfirobots.Main
api-version: '1.16'
authors: [ Dolfirobots ]
description: A little Proxy Security Plugin
website: Dolfirobots.net
commands:
  onlyproxy:
    description: The OnlyProxy command for reloading
    usage: /onlyproxy